In [1]:
import cv2
import numpy as np
import glob

cap = cv2.VideoCapture(0) #Указать номер камеры

if cap.isOpened() is True:
    i = 0
    while(True):
        ret, frame = cap.read()
        gray = cv2.cvtColor (frame, cv2.COLOR_BGR2GRAY) # Преобразовать в серый канал
        cv2.imshow('frame', gray)
        if i % 50 == 0:
            cv2.imwrite(''+ str(i) + '.png', gray)
        if (cv2.waitKey(1) & 0xFF == ord('q')) or (i==500):
            break
        i += 1
    cap.release()
    cv2.destroyAllWindows()

NameError: name 'b' is not defined

In [4]:
import numpy as np
import cv2 as cv
import glob
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((8*5, 3), np.float32)
objp[:, :2] = np.mgrid[0:8, 0:5].T.reshape(-1, 2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('*.png')
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (8,5), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
        # Draw and display the corners
        cv.drawChessboardCorners(img, (8,5), corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(500)
cv.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
import glob
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*6, 3), np.float32)
objp[:, :2] = np.mgrid[0:6, 0:6].T.reshape(-1, 2)
# Arrays to store object points and image points from all the images.
objpoints = []  # 3d point in real world space
imgpoints = []  # 2d points in image plane.
images = glob.glob('*.png')
i = 0
x = 6
y = 4
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (x, y), None)
    # If found, add object points, image points (after refining them)
    if ret:
        i += 1
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        for i in range(corners.shape[0]):
            z1 = int(corners[0,0,1])
            z2 = int(corners[0,0,0])
            z3 = int(corners[((x*y)-1),0,1])
            z4 = int(corners[((x*y)-1),0,0])
            #print(" -- Refined Corner [", i, "]  (", corners[i,0,0], ",", corners[i,0,1], ")")           
        imgpoints.append(corners)
        # Draw and display the corners
        cv2.drawChessboardCorners(img, (x, y), corners2, ret)
        cv2.imshow('img', img)
        print (z1,":",z3,",",z2,":",z4)
        cv2.imwrite(str(i)+'.jpg', img)
        cv2.waitKey(50)
        
cv2.destroyAllWindows()

In [5]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [26]:
# undistort
dst = cv.undistort(img, mtx, dist, None, newcameramtx)
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)
np.savez('calib.npz', mtx=mtx, dist=dist, rvecs=rvecs, tvecs=tvecs)

In [7]:
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[597.73323143   0.         316.61322496]
 [  0.         598.52519806 250.30351091]
 [  0.           0.           1.        ]]
dist : 

[[ 0.02944763  0.45204743  0.00231028 -0.00210941 -1.83664483]]
rvecs : 

(array([[0.00519201],
       [0.00688119],
       [0.11234866]]), array([[-0.00080927],
       [ 0.01246009],
       [ 0.65180467]]), array([[-0.63678437],
       [ 0.02239928],
       [ 0.19134966]]), array([[-0.63748124],
       [ 0.23738942],
       [-0.08113272]]), array([[0.26897055],
       [0.02508043],
       [0.16663543]]), array([[0.0046385 ],
       [0.00722593],
       [0.11233363]]), array([[-0.49053507],
       [ 0.07995127],
       [ 0.14698398]]), array([[ 0.10989517],
       [-0.03448629],
       [ 0.08432096]]), array([[ 0.19260753],
       [-0.01316771],
       [ 0.07985252]]), array([[-0.0023426 ],
       [ 0.01086825],
       [-0.08900831]]), array([[ 0.01726276],
       [-0.05332585],
       [-0.83512062]]), array([[0.04171638],
       [0.0