In [1]:
import cv2
import math
import numpy as np
import time

camera = cv2.VideoCapture(0)


cx2=0
cy2=0
A=0
while True:
    iSee = False     
    controlX = 0.0     
    success, frame = camera.read()  
    #frame_re = frame[138:361,218:476]
    #frame=frame_re
    if success:    
        height, width = frame.shape[0:2]   
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)    
        bin1 = cv2.inRange(hsv, (17, 158, 0), (35, 255, 255)) # желтый
        bin2 = cv2.inRange(hsv, (0, 158, 0), (16, 255, 255)) # красный
        bin3 = cv2.inRange(hsv, (36, 158, 0), (52, 255, 255)) # зеленый
        bin4 = cv2.inRange(hsv, (66, 158, 0), (108, 255, 255)) # голубой
        binary = bin1+bin2+bin3+bin4  
        roi = cv2.bitwise_and(frame, frame, mask=binary)   
        contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_NONE) 
        '''
        for i,cnt in enumerate(contours):
            M=cv2.moments(cnt) 
            x1,y1=cnt[0,0]
            img1=cv2.drawContours(frame, [cnt], -1, (0, 255, 255), 3) 
            cv2.putText(frame,f'Contour:{i+1}',(100,110),cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2, cv2.LINE_AA)
        '''  
        for i,cnt in enumerate(contours):
            if len(contours) != 0:  
                #maxc = max(contours, key=cv2.contourArea)  
                moments = cv2.moments(cnt) 
                if moments["m00"] > 20: 
                    cx = int(moments["m10"] / moments["m00"])  
                    cy = int(moments["m01"] / moments["m00"])  
                    cx2 = int((341/258)*cx)  # перевод пикселей в мм по оси x
                    cy2 = 291-(int((291/223)*cy)) # перевод пикселей в мм по оси y
                    iSee = True  
                    controlX = 2 * (cx - width/2) / width   
                    cv2.drawContours(frame, cnt, -1, (0, 255, 0), 2)  
                    rect = cv2.minAreaRect(cnt)
                    box = cv2.boxPoints(rect)
                    box = np.int0(box)
                    print(box)
                    #cv2.line(frame, (cx, 0), (cx, height), (0, 255, 0), 2)  
                    #cv2.line(frame, (0, cy), (width, cy), (0, 255, 0), 2)  
            cv2.putText(frame, 'Axes x: {};'.format(cx2), (width - 500, height - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2, cv2.LINE_AA) 
            cv2.putText(frame, 'Axes y: {}'.format(cy2), (width - 200, height - 100),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2, cv2.LINE_AA) 
            cv2.imshow('frame', frame)  # выводим все кадры на экран
            cv2.waitKey(1)
cv2.destroyAllWindows()
return(cx2,cy2,iSee)

[[127 460]
 [138 460]
 [138 467]
 [127 467]]
[[112 472]
 [120 467]
 [122 471]
 [115 476]]
[[113 455]
 [145 450]
 [147 461]
 [115 466]]
[[135 446]
 [142 442]
 [144 446]
 [137 450]]
[[125 462]
 [129 450]
 [140 454]
 [136 466]]
[[277 475]
 [293 475]
 [293 479]
 [277 479]]
[[277 474]
 [284 474]
 [284 479]
 [277 479]]
[[556 465]
 [575 465]
 [575 471]
 [556 471]]
[[414 474]
 [415 470]
 [440 474]
 [439 478]]
[[547 469]
 [557 469]
 [557 479]
 [547 479]]
[[515 469]
 [526 469]
 [526 478]
 [515 478]]
[[405 466]
 [408 459]
 [437 471]
 [434 478]]
[[540 456]
 [550 451]
 [552 455]
 [542 460]]
[[405 464]
 [406 459]
 [420 462]
 [419 466]]


KeyboardInterrupt: 